function [Q,H] = Arnoldi(A,b,n)
%{
A is any matrix
n is the number of iterations to be preformed. Note that n must be less
than or euqual to the number of columns of A.

H is the upper (n+1) by n upper-left section of the Hessenberg form of A

%}
[~,m] = size(A);
Q = zeros(m); %will store the orthogonal bases for the Krylov subspace
H = zeros(m); % will store the Hessenberg form of A
Q(1:m,1) = b/norm(b);
for i = 1:n;
    v = A*Q(1:m,i);
    for j = 1:i;
        H(j,i) = Q(1:m,j)'*v;
        v = v - H(j,i)*Q(1:m,j);
    end
    if norm(v) == 0; %if the norm of v is 0 then the Krylov subspace generated by b has now become an invarient
                     %subspace under A at this step.
        return;
    end;
    H(i+1,i) = norm(v);
    Q(1:m,i+1) = v/H(i+1,i);
end

