function [Q,H] = Arnoldi(A,b,n)
%{
A is any matrix

b is the starting vector (for eigenvalue problems b should be a random
vector, for solving systems of equations it will be specially chosen). 

n is the number of iterations to be preformed. Note that n must be less
than or equal to the number of columns of A.

H is the upper n+1 by n upper-left section of the Hessenberg form of A
Q is an orthonormal basis for the Krylov subspace A, Ab, (A^2)b,...
A^(n-1)b.

Convergence: the cnvergence rate of the Arnoldi iteration is not fully
understood and is aprt of curernt ersearch in numerical linear algebra (see
treffethen and Bau chapter 34). What can be said is that the characteristic
polynomail, p, of H will the the unique monic polynomail such that
||p(A)b|| is minimized, where ||.|| is the 2-norm.

%}
[~,m] = size(A);
Q = zeros(m); 
H = zeros(m); 
Q(1:m,1) = b/norm(b);
for i = 1:n
    v = A*Q(1:m,i);
    for j = 1:i
        H(j,i) = Q(1:m,j)'*v;
        v = v - H(j,i)*Q(1:m,j);
    end
    if norm(v) == 0 %if the norm of v is 0 then the Krylov subspace generated by b has now become an invarient
                     %subspace under A at this step.
        return;
    end
    H(i+1,i) = norm(v);
    Q(1:m,i+1) = v/H(i+1,i);
end

